### ISSUE TITLE
New to using program ( on WIndows) how do I lauch the game

### ISSUE THREAD

**Issue by ArgentumTempore** [vitor251093/KHDays_FM#100]
Got program to the 6th step don't know where to go to launch game.

**Comment by vitor251093** [comment]
Did you try to follow the "How to play" instructions from the homepage?

> First, download the [latest version](https://github.com/vitor251093/KHDays_FM/releases/latest) for your system (not the source code zip). Then, you will need an original copy of "Kingdom Hearts 358/2 Days" in order to dump it into a NDS file. Place that NDS file inside a "rom" folder, next to the downloaded Melon Mix executable (which was inside the zip file that you downloaded), and name it game.nds. Now you just need to launch the Melon Mix executable.

**Comment by ArgentumTempore** [comment]
I have attempted this and place files in ROM folder and attempted launch it tells me Failed to load ROM error in window. launching DLLS format Have 3080Ti. I'm a complete noob really first time messing with these programs.

**Comment by vitor251093** [comment]
Try naming the folder "rom", in lowercase

**Comment by ArgentumTempore** [comment]
(Then, you will need an original copy of "Kingdom Hearts 358/2 Days" in order to dump it into a NDS file. Place that NDS file inside a "rom" folder). Is this original file not listed as one of the downloads I keep getting the rom error and all im using is the info from the latest version link I don't know where I'm going wrong. Does anyone have a video guide to this im so lost.

**Comment by vitor251093** [comment]
> Is this original file not listed as one of the downloads

Well, yes. This is the NDS file, the ROM of the "Kingdom Hearts 358/2 Days" for the Nintendo DS. We can't give download links to it because that would be piracy.

**Comment by vitor251093** [comment]
So far, it seems this was just a misunderstanding of the instructions. I will close the issue, but if you still have problems, you can reopen this issue
