### ISSUE TITLE
Command Menu inputs should function as d-pad while the menu is open

### ISSUE THREAD

**Issue by JordanAClark** [vitor251093/KHDays_FM#103]
While the menu is open, and especially while the panels menu is open, it would be great if the inputs that are mapped to control the command menu simply functioned as the D-Pad inputs, since for many people it is second nature to navigate a grid menu like that with the D-Pad but with the current implementation if you have left stick mapped to move and D-pad mapped to command menu, trying to move left in the panel menu will close the menu and trying to move right will select the currently highlighted panel.

And not to be a back seat coder, but I assume this would be pretty simple to implement with a variable that gets turned on along with the same function that sets it to display both screens when opening the menu, and then when the player pushes the command menu buttons while the variable is true it treats them as D-pad inputs instead

**Comment by vitor251093** [comment]
Supposedly, that's already done in the latest builds. I'm not sure if it's in the last official release though 

https://github.com/vitor251093/KHDays_FM/blob/master/src/KHDays_Plugin.cpp#L44

**Comment by JordanAClark** [comment]
ah ok. I just downloaded the latest release today and it doesn't seem to be in that, but if you say it's in the latest build I believe you.

**Comment by JordanAClark** [comment]
Sounds like this is in the latest build

**Comment by vitor251093** [comment]
> but if you say it's in the latest build I believe you.

It should be at least, unless it's bugged. But I can't confirm right now
