### ISSUE TITLE
Game Crash when I Launch the .exe

### ISSUE THREAD

**Issue by Xane730** [vitor251093/KHDays_FM#109]
When I launch the .exe, the window opens for a few seconds on a black screen, but then it closes right after. I sent my .zip to a friend, and for him, it says there is a ROM problem, but it doesn't close the window, and he can choose his ROM from the software. It works when my friend selects the ROM located in the "rom" folder.

**Comment by vitor251093** [comment]
> When I launch the .exe, the window opens for a few seconds on a black screen, but then it closes right after.

Check if your issue is like this one (with the shaderfail file):
https://github.com/vitor251093/KHDays_FM/issues/92

> I sent my .zip to a friend, and for him, it says there is a ROM problem, but it doesn't close the window, and he can choose his ROM from the software. It works when my friend selects the ROM located in the "rom" folder.

Was the "rom" folder next to the Melon Mix exe, and the ROM itself named game.nds?

**Comment by Xane730** [comment]
> Check if your issue is like this one (with the shaderfail file): #92
I'll check this issue thanks !

> Was the "rom" folder next to the Melon Mix exe, and the ROM itself named game.nds?
Yes I did exactly as in the tutorial, with the right names

**Comment by vitor251093** [comment]
> Yes I did exactly as in the tutorial, with the right names

I meant if your friend named them correctly 😅 If the folder is named "rom" and the NDS file named "game.nds" (both lower case), the Melon Mix should have found the NDS file automatically.

**Comment by Xane730** [comment]
Oh I see, I checked the https://github.com/vitor251093/KHDays_FM/issues/92 probleme, and with the new build it fixed the problem thanks !!
