### ISSUE TITLE
Compute Shader Renderer 2 Screen bug

### ISSUE THREAD

**Issue by DaniKH1** [vitor251093/KHDays_FM#114]
The latest build on Compute Shader Renderer 2 has an issue with the screens.

![imagen_2024-05-24_112828334](https://github.com/vitor251093/KHDays_FM/assets/32207585/f881a2ad-8cb5-4a0b-a90c-1c458ab136ec)
![imagen_2024-05-24_112939360](https://github.com/vitor251093/KHDays_FM/assets/32207585/e379fd7c-67f4-458c-a75a-cc50063d8bcb)

**Comment by vitor251093** [comment]
Try switching the screen sizing to Top only. Auto used to be the default, but I changed that in some of the recent commits

**Comment by vitor251093** [comment]
Confirmed to be fixed in Top Only
