### ISSUE TITLE
D-Pad isn't working in the panels menu

### ISSUE THREAD

**Issue by UltimoSucco** [vitor251093/KHDays_FM#116]
i don't understand why the D-Pad work in the normal menu (where the combo with the X button should trigger the ability menu) but does not work in the panels menu (where the funcion is exacly the same) is there some code bug or something?
is just kinda frustrating not beedin able to use the D-Pad in that menu only (i hate use the stick in every menus to be honest)

https://github.com/vitor251093/KHDays_FM/assets/85536549/c605c221-e229-47f0-a459-d173b64aaf19

**Comment by vitor251093** [comment]
The D-Pad should now work in the panels menu. @UltimoSucco could you please confirm?

**Comment by UltimoSucco** [comment]
do i have to download the newest version?

**Comment by vitor251093** [comment]
You need to download the latest Actions build

https://github.com/vitor251093/KHDays_FM/actions/runs/9294627507

**Comment by UltimoSucco** [comment]
oh, ok, sry for the long wait, i'll try it now
