### ISSUE TITLE
Mac IOS questions

### ISSUE THREAD

**Issue by NewAgeHero7** [vitor251093/KHDays_FM#124]
which one is the Mac file and can you post a tutorial on the front page like the windows and steam deck one please as Macs can be more complicated

**Comment by NewAgeHero7** [comment]
Also what do you mean by ds file? do you mean a rom file or something else? I'm highly confused about that lol

**Comment by vitor251093** [comment]
Despite the fact that we now can make macOS builds, there wasn't a stable release of it instead.

Try using this build:
https://github.com/vitor251093/KHDays_FM/actions/runs/9274179030

The instructions should be the same ones you can find in the home page at "How to play".

> Also what do you mean by ds file? do you mean a rom file or something else? I'm highly confused about that lol

Yes, a Nintendo DS ROM, an .nds file.

**Comment by vitor251093** [comment]
Melon Mix 0.2.2 was released, with a macOS builds. Could you please confirm if the instructions are enough to make it work?
