### ISSUE TITLE
MacOS Download

### ISSUE THREAD

**Issue by adirubbo13** [vitor251093/KHDays_FM#126]
Hello, 

In the readme, it is noted that there is a MacOS version, however in the [download](https://github.com/vitor251093/KHDays_FM/releases/tag/v0.2.1) page there appears to not be a MacOS version.

**Comment by NewAgeHero7** [comment]
I have been wondering this as well plus on the main page the instructions are not clear, I'm not really a modder but I did manged to get melon ds on my Mac and it works fine but this seems way more complicaed and I hope he updates his main page soon for more info on Mac iOS

**Comment by vitor251093** [comment]
Despite the fact that we now can make macOS build, there wasn't a stable release of it instead.

Try using this build:
https://github.com/vitor251093/KHDays_FM/actions/runs/9274179030

The instructions should be the same ones you can find in the home page.

**Comment by vitor251093** [comment]
Melon Mix 0.2.2 was released, with a macOS builds. Could you please confirm if the instructions are enough to make it work?

**Comment by adirubbo13** [comment]
Yes, this works and is clear, thank you very much!
