### ISSUE TITLE
Possiblity to resize the dialogue boxes?

### ISSUE THREAD

**Issue by Draxirch** [vitor251093/KHDays_FM#139]
This is an amazing version to play.

This isn't an issue but a suggestion.

Was wondering is it possible to resize the dialogue boxes to be in the centre of the screen similar to the new awesome placement of the Mission objective?

This is such an amazing feat though!
Reinvigorating my desire to play this gem.

**Comment by vitor251093** [comment]
You know what, I never thought about that...

We could turn it into a floating dialog, like in other KH games.

It won't look exactly like them, but we can replicate the feel.

**Comment by vitor251093** [comment]
Concept of what we should implement

![mockup](https://github.com/vitor251093/KHDays_FM/assets/8976483/83d87a6b-32b3-4621-bbac-0527624ec97c)

Height reduced by 33% (should have a fixed height no matter the resolution). Centered in the X axis, and about 5% above the bottom (regarding the screen size). The corners should be created dynamically using shaders.

**Comment by Draxirch** [comment]
> Concept of what we should implement
> 
> ![mockup](https://private-user-images.githubusercontent.com/8976483/337373098-83d87a6b-32b3-4621-bbac-0527624ec97c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTAwNTksIm5iZiI6MTcxNzcwOTc1OSwicGF0aCI6Ii84OTc2NDgzLzMzNzM3MzA5OC04M2Q4N2E2Yi0zMmIzLTQ2MjEtYmJhYy0wNTI3NjI0ZWM5N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMjEzNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY3MzJjOWZjNGEwMzQ0Yjk4MGRjMzhlZmMxYmMxNTIyNjA4ZTVlMTBiNWQ1ZWZiN2EwYWFhNWY3NGMyZGUwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i0ATfcp6dmGnMWPs6NqW47vojLIsW94PNnYAM_d9Bu0)
> 
> Height reduced by 33% (should have a fixed height no matter the resolution). Centered in the X axis, and about 5% above the bottom (regardless of the screen size). The corners should be created dynamically using the fragment shader. The right corner of the portrait label will be a mirror of the left corner.

This is exactly what I wanted!

**Comment by vitor251093** [comment]
> Has anyone suggested resizing the information bar and keeping it on the left hand side like mainline KH games?

I think that was suggested back in the beginning of the fragment shader, but at that time, doing that was not possible, because it would require moving the heart points counter, and that counter is not renderer as 2D, but as 3D.

We can analyze the possibility of doing it right now though. Could you please

**Comment by Draxirch** [comment]
> > Has anyone suggested resizing the information bar and keeping it on the left hand side like mainline KH games?
> 
> I think that was suggested back in the beginning of the fragment shader, but at that time, doing that was not possible, because it would require moving the heart points counter, and that counter is not renderer as 2D, but as 3D.
> 
> We can analyze the possibility of doing it right now though. Could you please open a new issue for that?

Absolutely.

**Comment by vitor251093** [comment]
This change will be included in the next release, except for the rounded corners, which I will introduce in a future update. As of now, this is the current visual:

![2024-06-06_17-20](https://github.com/vitor251093/KHDays_FM/assets/8976483/6531a33a-2edc-4e96-966f-e1943885087c)
