### ISSUE TITLE
macOS build not working

### ISSUE THREAD

**Issue by erysmvn** [vitor251093/KHDays_FM#141]
mac version: [Sonoma 14.5 (23F79)]
ram: [8 GB]
processor: [Apple M2]

<img width="1680" alt="Screenshot 2024-06-04 at 10 51 05 AM" src="https://github.com/vitor251093/KHDays_FM/assets/124170570/dc5809ea-6470-451f-a865-729a0fa0bf6c">

can it be fixed or should i try the windows version?

**Comment by vitor251093** [comment]
For the next release, I'm going to include a new build, which should work as expected based on my tests

**Comment by vitor251093** [comment]
> For the next release, I'm going to include a new build, which should work as expected based on my tests

So, that was the plan, but I just realized I can create bundled macOS apps either, only those which require the Homebrew dependencies...

I will handle that at #146
