### ISSUE TITLE
HUD overlays in mission cutscenes (Holo-memory or Clock Stopped) cause a black screen during dialouge.

### ISSUE THREAD

**Issue by Ssheph95** [vitor251093/KHDays_FM#154]
**Describe the bug**
When playing in Mission Mode, any time story events with dialogue occur as a "holo-memory" cut-scene, the visible screen reduces to the width of the dialogue box, resulting in the majority of the screen being blacked out.

**To Reproduce**
Effectively the simplest way to observe this is to launch a game in mission mode (solo) and start mission 7. So long as you don't press "start" to skip the cut-scene, you'll see the reduction as soon as Axel's dialogue with Roxas about their mission begins.

**Expected behavior**
The overlay should operate as it does in story mode game-play, allowing the scene to be viewed as normal.

**Screenshots**
![image](https://github.com/vitor251093/KHDays_FM/assets/97009666/ca113da6-f5cd-41a3-bebe-4bccb623183f)
![image](https://github.com/vitor251093/KHDays_FM/assets/97009666/0ebeb54b-32f8-4501-b783-dc4408ee9a25)
Here you see the scenes operating as normal without dialogue. Missions 7 and 14

![image](https://github.com/vitor251093/KHDays_FM/assets/97009666/cf7e707b-97bf-4c6b-a056-dc4bd6b0a418)
![image](https://github.com/vitor251093/KHDays_FM/assets/97009666/9a68329e-0ed3-4e1a-b861-ac3e6c755e2f)
Here you see the reduced screen when dialogue is present, Missions 7 and 14

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Melon Mix Version: Action release Windows#316

**Additional context**
I suspect that in regular story mode, there is no HUD layer before gaining control of the player, or this issue would exist there as well. Because the "holo-memory" label appears to be an HUD element, some interaction of the HUD resizing or dialogue box resizing code is causing a conflict when both are present in cut-scenes.

**Comment by Ssheph95** [comment]
![image](https://github.com/vitor251093/KHDays_FM/assets/97009666/8314ab1b-f0b0-4708-94d2-26a8eca05628)
New update, This also occurs in challenge missions during story mode with the "clock stopped" HUD overlay.

**Comment by vitor251093** [comment]
Fixed
