### ISSUE TITLE
Game displays in 5:3 instead of adapting to the fullscreen window size

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#16]
the game currently appears like this (16:9 squished into 5:3) :
![Screenshot (216)](https://github.com/vitor251093/KHDays_FM/assets/70611518/97d1e715-48e6-4d1d-a272-b0ac0ca8c933)

it should instead appear like this (true 16:9) :
![melonDS 2023-06-15 22-12-50](https://github.com/vitor251093/KHDays_FM/assets/70611518/38c074e0-79f8-44ec-a3a4-37ff51d4ca47)

for reference , this is how the game looks in 4:3 (notice how the picture lines up the same as 16:9 , just here with a smaller aspect ratio) :
![melonDS 2023-06-15 22-30-16](https://github.com/vitor251093/KHDays_FM/assets/70611518/fafacf4c-1a48-409e-8568-b535f9a3b2e8)

i submitted a pull request that includes an optimized 16:9 code but not sure how to set the aspect ratio to 16:9 by default instead of 5:3

**Comment by vitor251093** [comment]
> i submitted a pull request that includes an optimized 16:9 code but not sure how to set the aspect ratio to 16:9 by default instead of 16:10

The two lines that your pull request removes are some kind of cleaning of cache or memory, if I remember correctly. The second line, which is the one which really changes the resolution, is still the same. Also, the widescreen hack changes the proportion of the content of the rendered area, not the proportion of the rendered area itself.

The actual fix for the bug would be updating this:
```
Config::ScreenAspectTop = (size == screenSizing_Even) ? 0 : 4; // 4:3 / window size
```

To this:
```
Config::ScreenAspectTop = (size == screenSizing_Even) ? 0 : 3; // 4:3 / window size
```

Which is the actual correct index for window size.

I would update the code with that right now, but I noticed that, if I do that, the minimap breaks completely. Probably related to https://github.com/vitor251093/KHDays_FM/issues/5

**Comment by sandwichwater** [comment]
ah gotcha , that makes a lot more sense , thanks for the explanation . guessing it would require more testing to get it to work properly ¿

**Comment by vitor251093** [comment]
Indeed. But until the minimap issue can be sorted, it's better to keep it with that resolution to avoid a bigger issue.

Also, just clarifying: it's not rendering in 16:10, it's actually 5:3, which is the 3DS resolution. It's almost the same though.

**Comment by sandwichwater** [comment]
gotcha , i understand , its the start of a bigger journey for a truly definitive days experience after all

> The two lines that your pull request removes are some kind of cleaning of cache or memory, if I remember correctly. The second line, which is the one which really changes the resolution, is still the same in your code and mine; both use 16:9

also yea my bad , i just now realized your middle line of the code and my code are the exact same . my mind completely skipped that , thats on me

**Comment by vitor251093** [comment]
After fixing the minimap issue, and allowing the Melon Mix to use the configured top screen resolution as the top screen resolution when it's shown individually, this issue was finally solved.

**Comment by sandwichwater** [comment]
not sure if this is fixable but now it also stretches out the minimap no matter what the lower screen aspect ratio is , not sure if its intentional

**Comment by vitor251093** [comment]
It was. Since the whole in-game UI stretches when we change the resolution, I made it that so it looks as part of that same UI, so it's proportional to the window.

But yeah, it looked better before. I will create a new issue to fix the stretched UI as whole, so we can make the minimap stop stretching, along with the rest of the UI elements.
