### ISSUE TITLE
moogle shop currently only appears as one screen

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#17]
the moogle shop only displays the top screen like this :
![Screenshot (222)](https://github.com/vitor251093/KHDays_FM/assets/70611518/cbcaa9d6-bbbd-4afd-82df-f667b6b5fdcd)

when it should be displayed side by side like this :
![Screenshot (223)](https://github.com/vitor251093/KHDays_FM/assets/70611518/8fefeb94-f3d2-46b6-8020-aae83fa90ce2)

**Comment by vitor251093** [comment]
Just added a fix for the moggle shop. It doesn't fix the tutorial screen that appear right before the moggle shop though, which is identified as a minimap.

**Comment by sandwichwater** [comment]
does work , but for some reason changes back to single screen when hovering over some specific items in the shop

**Comment by vitor251093** [comment]
Can you give me an example of an item which has that issue so I can reproduce?

**Comment by sandwichwater** [comment]
sure , just woke up so im away from my pc but off the top of my head i remember potion bugs it out until switching categories in the "buy" , omega gear and omega gear plus bugs it out until switching off in the "sell" menu , and slot released bugs it out throughout several items in the "redeem" menu . i think also haste level+ and a few others in the "redeem" menu but id have to double check , the ones i listed are the ones i know for sure though

**Comment by vitor251093** [comment]
Just pushed a fix that should make the shop usable, including the tutorial that comes before using it for the first time (that one is not perfect yet, since there is a fraction of a second where you can see the tutorial as a minimap, but it's better than it was before).

**Comment by sandwichwater** [comment]
so sorry for the late reply , yes all seems to work fine👍
