### ISSUE TITLE
Missions screen doesn't work properly on day 357

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#18]
for some reason the emulator detects the bottom screen as a map and tries to crop it as such instead of displaying side by side :
![Screenshot (226)](https://github.com/vitor251093/KHDays_FM/assets/70611518/2987fb78-8974-4ec7-b3f5-51a50ea88fbe)

the same thing happens in the holo mission , saix mission , and challenge mission screens as well

**Comment by vitor251093** [comment]
The last fix in the master branch should have fixed this issue. Can you please verify?

**Comment by sandwichwater** [comment]
mostly , it still glitches out when switching between worlds and in the holo missions menu it requires you to click select in order for it to bring up the list , though it doesnt get detected as a minimap anymore :

https://github.com/vitor251093/KHDays_FM/assets/70611518/496aa01a-9535-4671-aac1-610a91ed499a

https://github.com/vitor251093/KHDays_FM/assets/70611518/fa35025c-1032-43d0-a15e-93bb9baa43d9

**Comment by vitor251093** [comment]
Ok, this one was easy to reproduce xD

Fixed both issues. And I've also fixed the black screen frames that were happening between scene changes.

Btw, if you uncomment this line from CMakeLists.txt and then build the project:
```
#set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_DEBUG")
```

The resulting build will show at the top left which scene is currently being loaded. Not useful for people who are playing the game, but very useful for debugging.

**Comment by sandwichwater** [comment]
hmm so , black flickers are fixed now its stuttering a lot when switching between worlds and in other places , for example when pausing , switching menus , loading into the game , basically whenever a new screen is loaded , though oddly enough its only happening in the compute shader , no stutters at all with the opengl renderer



> Btw, if you uncomment this line from CMakeLists.txt and then build the project:
> 
> ```
> #set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_DEBUG")
> ```
> 
> The resulting build will show at the top left which scene is currently being shown. Not useful for people who are playing the game, but very useful for debugging.

this is actually really helpful

**Comment by sandwichwater** [comment]
i think ive figured out the source of this bug , it only seems to happen on day 357 , right after roxas leaves the castle and right before his fight with xion . something about the hub room being in twilight town , as it doesnt happen when the hub room is in the world that never was

**Comment by vitor251093** [comment]
@sandwichwater would you have a save file for day 357, so I can take a closer look?

**Comment by sandwichwater** [comment]
sorry for the late response , here ya go
[game.sav.zip](https://github.com/vitor251093/KHDays_FM/files/14532142/game.sav.zip)

**Comment by vitor251093** [comment]
Fixed it
