### ISSUE TITLE
minimap covers some ui elements

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#19]
in mission mode and challenge mode the minimap covers up the death count and challenge sigils :
![Screenshot (231)](https://github.com/vitor251093/KHDays_FM/assets/70611518/65ebc909-cca5-422f-b9b5-8b970ab74373)
![Screenshot (229)](https://github.com/vitor251093/KHDays_FM/assets/70611518/2832ef91-bf64-4344-8a28-aed98fc88554)

**Comment by vitor251093** [comment]
I can place it a little lower. That should make those visible. It will be a bit distant from the top right corner, but I guess it's better to keep it usable.

**Comment by vitor251093** [comment]
Just submitted a change to the master branch which should fix that.

**Comment by sandwichwater** [comment]
yep that seems to work perfectly , it is a bit low yea but better to have it lower than it covering other parts of the game
