### ISSUE TITLE
Making all Regions Compatible

### ISSUE THREAD

**Issue by CodedRubyChan** [vitor251093/KHDays_FM#20]
I wanted to use the KH358MM Emu with an European ROM but it only works with the US ROM

I would love to see Multi-Region Support, but its not a big deal if its never coming

**Comment by vitor251093** [comment]
I just need to know the European game code to add it to the list of acceptable game codes. The American game code, for instance, is 1162300249

**Comment by CodedRubyChan** [comment]
i don't know how to check this, which program do i need?

**Comment by vitor251093** [comment]
I can't remember how exactly I checked mine, but one can do it using our current codebase if you add a print before the game code validation, or maybe an error message.

I can add that to a release, so you can retrieve the game code.

**Comment by CodedRubyChan** [comment]
then i'll wait for the updated source code and post then the game code here

**Comment by vitor251093** [comment]
The current version should show the game code in the logs, if you make a debug build. Can you run it that way in your computer?

**Comment by vitor251093** [comment]
Added support for the European and Japanese versions of the game. I'm not sure if there are any other versions.

A disclaimer though: the Japanese version seems to have a problem in the main menu. The European version seems to be working fine though.

**Comment by CodedRubyChan** [comment]
Perfect, will try the newest version^^
