### ISSUE TITLE
some prerendered cutscenes display improperly

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#24]
a few things regarding the prerendered cutscenes ive experienced , i hope i express these well enough and if not i can explain more :

the scenes that play on both the top and bottom screen currently display side by side , some examples are the opening , the scenes "snarl of memories" , "riku turns into ansem" , and "after the battle" to give some examples . i know youd be missing out on whats playing on the bottom screen but for the sake of having it as close to a full single screen experience in the style of the remaster i think it should focus on just the top screen during these scenes

similarly , scenes that play on just the bottom screen display side by side too despite there not being anything on the top screen at all so the focus should be on the bottom screen only

lastly , the final scene//credits scene "the usual spot" should display just the top screen as well , as the only thing really lost during the credits section on the bottom screen is a few textures , which can just be restored to show on a single screen anyways when texture replacement is fully functional , this can be applied to the opening too where when replaced with the remastered opening , the parts missing from the bottom screen are restored to the top screen

**Comment by vitor251093** [comment]
> the scenes that play on both the top and bottom screen currently display side by side , some examples are the opening , the scenes "snarl of memories" , "riku turns into ansem" , and "after the battle" to give some examples . i know youd be missing out on whats playing on the bottom screen but for the sake of having it as close to a full single screen experience in the style of the remaster i think it should focus on just the top screen during these scenes

> lastly , the final scene//credits scene "the usual spot" should display just the top screen as well , as the only thing really lost during the credits section on the bottom screen is a few textures , which can just be restored to show on a single screen anyways when texture replacement is fully functional , this can be applied to the opening too where when replaced with the remastered opening , the parts missing from the bottom screen are restored to the top screen

I've decided to keep both screens for two reasons. The first one is that it would be complicated to switch between them to keep the most important part visible. The second is because, like you mentioned, replacing those cutscenes with the remastered ones will solve the dual screen issue already, since it will combine both videos into one. So, imo, we should wait until cutscenes are replaceable to fix that one.

> similarly , scenes that play on just the bottom screen display side by side too despite there not being anything on the top screen at all so the focus should be on the bottom screen only

I've added a fix yesterday that should have fixed that scenario. Could you please check if that issue is still happening with the latest master branch build?

**Comment by vitor251093** [comment]
> seems to still be happening unfortunately

Can you give me an example of a cutscene which has that issue, so I can reproduce it?

**Comment by sandwichwater** [comment]
sure , mission 56 on day 193 , a bottom screen cutscenes happens right before the destroyer fight after xion collapses

**Comment by vitor251093** [comment]
I couldn't reach that mission in my save yet, but I've added a fix for the theater mode which should work for that issue as well. Could you check if it works properly now?

**Comment by sandwichwater** [comment]
theatre mode is fixed but bottom screen cutscenes are still showing in side by side mode instead being the focus as a single screen . if it helps , heres are some examples of whats happening :

https://github.com/vitor251093/KHDays_FM/assets/70611518/249e80fd-1100-4eac-a874-2b4a9fc1a9f8


https://github.com/vitor251093/KHDays_FM/assets/70611518/dbbd7ea1-21f4-42d9-b7f0-f4404b8d169b

**Comment by vitor251093** [comment]
@sandwichwater I think this issue may be already solved in the master branch build (new commits since v0.2.0). Could you please confirm?

**Comment by sandwichwater** [comment]
sorry for the late response , its fixed now👍
