### ISSUE TITLE
playing theatre mode cutscenes plays every cutscene side by side

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#25]
when a cutscene is played through theatre mode it plays in side by side mode by default , even when its shown as a single screen when played normally in missions

**Comment by sandwichwater** [comment]
mhm sure
[game.sav.zip](https://github.com/vitor251093/KHDays_FM/files/11790024/game.sav.zip)

**Comment by vitor251093** [comment]
Fixed it. I mean, it isn't perfect with the "Opening" cutscene, because at some point it does have two screens, but it works properly for the cutscenes which only play in the top screen

**Comment by sandwichwater** [comment]
yep , works perfectly👍
