### ISSUE TITLE
some textures dont get dumped due to duplicate hashes

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#28]
im not sure why this happens as theyre not the same item panel but for some reason textures get dumped with the same exact hash as other items , meaning either one or the other gets dumped and the texture gets applied to both ingame . for example , blazing shard has the same hash as lightning shard , meaning when one is replaced , they both get replaced , and if i delete the dumped texture for blazing shard , lightning shard shows up in its place with the same exact hash . oddly enough it only happens with item panels , every other texture is dumped just fine , theres a lot of other panel textures that dont get dumped that im almost certain is due to duplicate hashes

**Comment by sandwichwater** [comment]
similarly , replacing the skybox texture also changes zexions mystery gear pages , as both are invisible textures , the sky is done with post lighting effects . however this isnt really a problem as zexions mystery gear pages are supposed to be invisible and the skybox doesnt really need to be changed

**Comment by vitor251093** [comment]
Damn... I thought I had found identifier for the textures, but I guess I was wrong. I will need to make a deeper analysis.

**Comment by sandwichwater** [comment]
the weird thing is that its literally just the panels , everything else dumps just fine , maybe its possible they simply share the same string of numbers only at the start and is different past that ¿

**Comment by vitor251093** [comment]
Could be. But still, it means I'm using an unreliable identifier

**Comment by vitor251093** [comment]
This bug is now fixed
