### ISSUE TITLE
new build implementing command menu control via dpad not opening on windows

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#29]
if it makes any difference im testing the lastest build in the "actions" tab as opposed to building myself

**Comment by sandwichwater** [comment]
nevermind , it does , it just takes an insanely long time to launch . i tried again today and honestly forgot i tried to open it until it opened out of nowhere , tried it again to confirm this and yea , it just takes a long time to start up . my apologies

**Comment by vitor251093** [comment]
Maybe it's worth investigating why is it taking so long to launch? It opens almost instantly in my Debian computer, but there may an issue going on

**Comment by sandwichwater** [comment]
they work well , ill give more thoughts in the issue you created for it👍

**Comment by sandwichwater** [comment]
my  apologies , i also forgot to mention it only happens after the initial startup right before  the warning message , but opens almost instantly like you said after every subsequent startup . still , not sure why

**Comment by vitor251093** [comment]
Oh, well, in that case the slow down was probably a Windows issue, rather than an issue with the app. Let's keep it closed for now
