### ISSUE TITLE
Screen sizes and positions should switch automatically according to the needs

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#3]
Currently, this already happens, but we still need to confirm if that is currently covering all scenarios.

**Comment by sandwichwater** [comment]
is the windows version still bugged ¿ id love to be able to confirm everything as working properly but unfortunately it doesnt seem to want to launch still

**Comment by vitor251093** [comment]
> is the windows version still bugged ¿ id love to be able to confirm everything as working properly but unfortunately it doesnt seem to want to launch still

Since I don't have a Windows computer at my disposal, I'm not really sure. If you are still having issues with the latest build, can you confirm if the latest melonDS automated build has the same issue as well?

**Comment by vitor251093** [comment]
Sorry, I forgot to mention one thing: the issue seems to be directly related with OpenGL rendering, so you need to enable it in melonDS video settings in order to be sure.

**Comment by sandwichwater** [comment]
yep opengl runs just fine , its the only way i can play comfortably so i can confirm it works normally , though now im thinking ... if opengl is enabled on startup for daysmm by default maybe make a test build where its set to the software renderer on startup and i can see if simply changing it to opengl afterwards works ¿

**Comment by vitor251093** [comment]
This issue will be solved by completing the issues with the "display mode issue" label, so it's irrelevant to keep this one going
