### ISSUE TITLE
Some cutscenes (& gameplay moments) rendering incorrectly (yes those cutscenes, different bug)

### ISSUE THREAD

**Issue by AZX3400** [vitor251093/KHDays_FM#30]
Any time the "guy in red" is shown the game flickers between displaying minimap view and even view every frame. I've been loving this port/hack/whatever and am almost done with my first playthrough, Would love it if this was fixed soon. This should probably be high priority because it would definitely be seizure inducing to somebody with epilepsy. That said, it has given me the idea that maybe you should just overlay the bottom screen at 50% capacity since that's essentially what it did and besides the flashing and double roxas it worked pretty well. Just please don't completely hide the bottom screen during these like someone else suggested in #24 , that's removing part of the game.

**Comment by sandwichwater** [comment]
heya friendly heads up , an issue for this already exists #23 though it seems like it doesnt display as completely black anymore , just flickering like you described . though yea it should be high priority , something like what you suggested would be perfect , or alternatively something similar to how tutorials work in the sense that it can detect when the static texture shows on screen , emphasize that to be the main screen , then switch back to roxas view when the static texture is not displayed anymore . but yes i agree , bottom screen moments with sora should not be hidden and ideally the game should change emphasis to those moments without needing to have a side by side view

**Comment by vitor251093** [comment]
I will try to take a look at that issue during this week, along with #28 and #29

**Comment by vitor251093** [comment]
@sandwichwater I'm sorry, but could you also validate if that one is still happening? xD
