### ISSUE TITLE
Controlling the Command Menu using a D-pad

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#31]
This is a usual behavior in KH games, but on Days it wasn't possible due to limitations of the console.

There is, however, an ingame setting which allows the player to control the command menu by pressing the D-pad, as long as the X button is being held.

We added a functionality that takes use of it, by allowing the player to set the up/down buttons that should control the command menu. While pressing those, MelonMix press X, releases the D-pad directionals, and then, two frames later, press the D-pad equivalent direction. I tried to do it instantly, but then the game recognizes it as movement, rather than a command menu direction.

This has a small side effect: if the player is moving closer to the camera, but presses the command menu up button, the player stops walking down for a fraction of a second, but instantly resumes that movement. It doesn't seemed noticable in my tests, by it's better to have a second opinion.

Also, if the player holds the command menu up directional, instead of just pressing it, the player stops moving up/down until it's released.

Either we consider those ignorable, and fix the most significant issue with that approach (the fact that this in-game option is not enabled by default, which may be solvable with a cheat). Or we change the approach entirely, by just pressing X to move down, and doing a memory injection to move the directional upwards (which I currently have no idea on how to do).

**Comment by sandwichwater** [comment]
i feel like while it is an issue , it doesnt make the game impossible or unbearable to play , so for now it should be on the work in progress list to fix eventually . though that being said , you can also navigate the menus left and right for example in the magic and items menu with x + left and x + right respectively , which should also be controllable , though i can imagine that may introduce more movement issues

**Comment by vitor251093** [comment]
> i feel like while it is an issue , it doesnt make the game impossible or unbearable to play , so for now it should be on the work in progress list to fix eventually

Fair

> though that being said , you can also navigate the menus left and right for example in the magic and items menu with x + left and x + right respectively , which should also be controllable , though i can imagine that may introduce more movement issues

What if I use B/A as the behavior for the left/right command menu D-pad? If that works, it wouldn't have movement issues

**Comment by vitor251093** [comment]
> What if I use B/A as the behavior for the left/right command menu D-pad? If that works, it wouldn't have movement issues

Just added that feature. Seems to be working properly.

**Comment by sandwichwater** [comment]
it does work , though when not on a menu that can be navigated left and right you jump and attack . still low priority issue as is techinically does work albeit buggy , but figured id let you know

**Comment by vitor251093** [comment]
> it does work , though when not on a menu that can be navigated left and right you jump and attack

Yeah, I thought about that. Still, I considered it less buggy than using Left/Right, since that may cause the movement issue.

Obviously not perfect though.

**Comment by vitor251093** [comment]
In order to complete this ticket, as at least functional, we need a cheat code to keep enabled the in-game option that allow using X + D-Pad to control the command menu. Currently looking for a way to create it.

**Comment by vitor251093** [comment]
Thanks to Reddit, I figured out what I was doing wrong.

https://www.reddit.com/r/ActionReplay/comments/18sux3t/comment/kfcb6e7/?context=3

Now this feature doesn't need a manual adjust anymore, and even if the user changes that option in the menu, it will just change back to the functional option.

**Comment by vitor251093** [comment]
I should fix the Windows build next in order to prepare a new release.
