### ISSUE TITLE
In-game HUD shouldn't stretch

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#34]
Currently, the in-game HUD stretches according to the selected resolution. It would be preferable if, like in modern games, it could keep a specific size no matter the resolution (aka if the resolution gets bigger, the HUD looks smaller).

**Comment by CpazR** [comment]
Is this also something that texture replacements could fix? Even if in a hacky sort of way?

**Comment by vitor251093** [comment]
Made a huge progress in that ticket this night.

![2024-01-30_01-33](https://github.com/vitor251093/KHDays_FM/assets/8976483/54c7dc85-6ff0-4559-bb87-c10403847083)

**Comment by sandwichwater** [comment]
very promising !

**Comment by vitor251093** [comment]
Now that I've figured exactly how to do it, I just need to adapt it to the different UIs (Mission Complete label, mission details label, pause screen menu, etc).

Won't be able to work on that tonight, but will check it out tomorrow.

**Comment by vitor251093** [comment]
https://github.com/vitor251093/KHDays_FM/assets/8976483/a509aa4c-c9bd-4e95-9545-13b903f7769a

**Comment by vitor251093** [comment]
Many changes aiming at better replicating the look and feel of the other games:
- The HUD elements are now more distant from the border
- The minimap is now shown in negative (may look better with some adjustments)
- Ingame pause screen options were scaled down like the HUD elements

Next objectives:
- Improve minimap, by keeping the color of elements that are not in grayscale
- Add the minimap to the top screen using shaders, instead of adding the bottom screen on top of the top screen and then cropping the bottom sreen

**Comment by sandwichwater** [comment]
i went and grabbed some reference images from kh2 to help get a more accurate size of the hud and pause menu , these look a bit small at the moment ![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/e7b098b9-0ebf-4b89-83dc-f1d56f3b2b74)
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/c5ba6cc8-e162-4293-bdfa-099517366731)

as for the command menu placement i feel like it should still come a bit away from the left of the screen like you changed it but still sit at the bottom like in the original game , the way it the back layer of it drops down makes it look more natural sitting at the bottom

**Comment by vitor251093** [comment]
> i went and grabbed some reference images from kh2 to help get a more accurate size of the hud and pause menu , these look a bit small at the moment

I can add a setting to configure the HUD size. As of right now, I actually used a KH3 screenshot as reference for the size of the HUD, and it's actually bigger than KH3's xD

> as for the command menu placement i feel like it should still come a bit away from the left of the screen like you changed it but still sit at the bottom like in the original game , the way it the back layer of it drops down makes it look more natural sitting at the bottom

I'm not that sure about that. If I move it to the bottom, I will need to move the life bar to the bottom as well, otherwise it's going to look weird. I can take a screenshot simulating that if you want to see.

I agree that the bottom part of the command menu looks a bit unnatural floating like that, but maybe it would be better to replace its texture in the future with a high res one that actually doesn't feel weird floating.

**Comment by sandwichwater** [comment]
> I can add a setting to configure the HUD size. It will probably be good for accessibility as well. As of right now, I actually used a KH3 screenshot as reference for the size of the HUD, and it's actually bigger than KH3's xD

ah i felt like the sizing looked familiar lol , its definitely cool seeing it that small but maybe for practical purpose it seems a bit *too* small , atleast as a default , setting would probably be best

just for the sake of doing it as well , i did a quick mockup of the hud with kh2 sizing and placement just to have a reference :
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/98bd5fab-2a01-4c4e-8ebe-be2cea425b60)

compared to the original sizing and position :
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/895a1f6b-4e50-4425-a761-b7d7f081ddba)

**Comment by vitor251093** [comment]
> just for the sake of doing it as well , i did a quick mockup of the hud with kh2 sizing and placement just to have a reference

That actually looks better then I imagined. I will make some tests making the command menu touch the bottom on bigger resolutions to see if it will still look good.

**Comment by vitor251093** [comment]
> ah i felt like the sizing looked familiar lol , its definitely cool seeing it that small but maybe for practical purpose it seems a bit too small , atleast as a default , setting would probably be best

Sure, I can make the default a bigger size :)

**Comment by vitor251093** [comment]
![2024-02-01_21-38](https://github.com/vitor251093/KHDays_FM/assets/8976483/60342a9b-0408-4c80-9888-40fb67eaa30d)

@sandwichwater I've applied all the changes we talked about. What do you think?

**Comment by sandwichwater** [comment]
looks good👍 , my only concern at the moment is the map seems like it would cover up the challenge sigils or mission mode death counter , or was that already accounted for ¿

**Comment by vitor251093** [comment]
> looks good👍 , my only concern at the moment is the map seems like it would cover up the challenge sigils or mission mode death counter , or was that already accounted for ¿

That's already accounted for. Although, I haven't tested, so my measures may be wrong xD

Still, considering that now we have control over the 2D UI, I think it would be better to move the challenge sigils and the mission mode death counter, so they are placed below the minimap. What do you think?

**Comment by sandwichwater** [comment]
> I think it would be better to move the challenge sigils and the mission mode death counter, so they are placed below the minimap. What do you think?

we could try that , just not sure how natural it would look ... though i guess with as many ui elements that days have it would be hard to make it look natural either way lol . maybe underneathe the heart counter ¿ theres a timer that appears under the coliseum training missions but placed under the timer might work

or maybe the sigils and deaths could be placed in the same location right between the enemy hp and the map since theres no scenario where they both appear at the same time so there would be no overlap🤔

lots of possibilities lol , im curious to see how the sigils and death counter look with your current implementation though

**Comment by vitor251093** [comment]
> or maybe the sigils and deaths could be placed in the same location right between the enemy hp and the map since theres no scenario where they both appear at the same time so there would be no overlap🤔

Sounds good to me

> im curious to see how the sigils and death counter look with your current implementation though

Just took some screenshots after tweaking the positions a little bit.

![2024-02-01_22-15](https://github.com/vitor251093/KHDays_FM/assets/8976483/8dea0dca-11d9-49cb-aaec-c000025a3161)
![2024-02-01_22-15_1](https://github.com/vitor251093/KHDays_FM/assets/8976483/157365aa-8b2b-45f8-94e6-90ea7381ee43)
![2024-02-01_22-16](https://github.com/vitor251093/KHDays_FM/assets/8976483/bd35a1e2-ebbe-4961-b093-b0a20dd95ca3)

**Comment by CpazR** [comment]
> > or maybe the sigils and deaths could be placed in the same location right between the enemy hp and the map since theres no scenario where they both appear at the same time so there would be no overlap🤔
> 
> Sounds good to me
> 
> > im curious to see how the sigils and death counter look with your current implementation though
> 
> Just took some screenshots after tweaking the positions a little bit.
> 
> ...
> 
> I just need to test the sigils now

I am curious if the hud stretch is just something to live with or if jt can be fixed. But it's looking great so far!

**Comment by vitor251093** [comment]
> I am curious if the hud stretch is just something to live with or if it can be fixed. But it's looking great so far!

It's definitively possible to fix. In fact, I tried to do it, but I had some problems accessing the aspect ratio variable.

**Comment by sandwichwater** [comment]
seems like the enemy name gets cut off by one pixel at the top , otherwise it all looks great , death counter looks natural underneathe the map

**Comment by vitor251093** [comment]
> seems like the enemy name gets cut off by one pixel at the top

Fixed that

> otherwise it all looks great , death counter looks natural underneathe the map

Great! :D I will test the sigils in a while

**Comment by vitor251093** [comment]
I had to make a small adjustment, but the sigils look good now as well

![2024-02-01_23-09](https://github.com/vitor251093/KHDays_FM/assets/8976483/764e83e9-8af1-44a9-8561-c38106cf4629)
![2024-02-01_23-10](https://github.com/vitor251093/KHDays_FM/assets/8976483/45bdd4ee-fc81-4594-a514-45e8ffc827b1)

**Comment by vitor251093** [comment]
It's worth noting that the recent changes caused glitches in screens which still need proper game scenes. Among them:
- The Continue/Withdraw death screen
- The introduction screen of a Challenge
- The "Press A" screen after exiting a Holo-Mission in Mission Mode

That needs to be fixed before this feature is merged into the master branch.

**Comment by vitor251093** [comment]
> I am curious if the hud stretch is just something to live with or if it can be fixed

![2024-02-02_01-07](https://github.com/vitor251093/KHDays_FM/assets/8976483/9e6a2761-885c-4eb0-9b13-4ed9f8c08d38)

I've de-stretched the player health, the command menu, and the minimap content (not finished; it currently uses a hard coded aspect ratio). Although, it looks a bit off to me. Specially the command menu.

**Comment by sandwichwater** [comment]
hmm yea theyre both squished a little bit too much

**Comment by vitor251093** [comment]
![2024-02-02_01-39](https://github.com/vitor251093/KHDays_FM/assets/8976483/76045cf5-1d30-4a5d-ab2c-463a83fe160c)

Ok, it actually doesn't look that bad, now that I can use the real aspect ratio.

**Comment by vitor251093** [comment]
The only issue right now with the de-stretching method is that it relies on a function that updates the aspect ratio variable, and that causes a concurrency issue, so the stretch is only reverted correctly after a game scene change

**Comment by vitor251093** [comment]
Alright. Fixed all the issues related to stretching. Now it looks good no matter the aspect ratio for the command menu, the player health, and the minimap. I just need to adjust the other elements so they are adapted in the same way, and then I can get back to this:

> It's worth noting that the recent changes caused glitches in screens which still need proper game scenes. Among them:
> 
> * The Continue/Withdraw death screen
> * The introduction screen of a Challenge
> * The "Press A" screen after exiting a Holo-Mission in Mission Mode
> 
> That needs to be fixed before this feature is merged into the master branch.

After that, this issue will be completed.

**Comment by vitor251093** [comment]
Ok, now only the introduction screen of a Challenge has an issue

**Comment by vitor251093** [comment]
Change completed. Images for evidence.

![2024-02-02_14-49](https://github.com/vitor251093/KHDays_FM/assets/8976483/e32f413d-15d7-41a7-8890-485ab5c8b576)
![2024-02-02_14-49_1](https://github.com/vitor251093/KHDays_FM/assets/8976483/0010e842-35f3-4fbd-9a13-11cb8f9d5199)
![2024-02-02_14-50](https://github.com/vitor251093/KHDays_FM/assets/8976483/89d2a651-45c4-495c-ad92-70ee359d1aa0)
![2024-02-02_14-50_1](https://github.com/vitor251093/KHDays_FM/assets/8976483/10ff3dba-9de9-4fa4-b306-77e2ec288340)
![2024-02-02_14-50_2](https://github.com/vitor251093/KHDays_FM/assets/8976483/3aec44f4-c230-4262-83c3-7a3b40af077b)
![2024-02-02_14-50_3](https://github.com/vitor251093/KHDays_FM/assets/8976483/a7a03ca9-f41a-490a-826d-bd5bd3a62264)
