### ISSUE TITLE
screen flashes when choosing save file and has incorrect emphasis when hovering over guest play

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#35]
ive been holding off on reporting this since it doesnt seem as much of a priority but figured i probably should sooner rather than later . 
not sure how well the flashing shows here since it really is for just a fraction of a second but the screen shows in horizontal mode when the pointer is over guest play in mission mode

https://github.com/vitor251093/KHDays_FM/assets/70611518/704e3c7d-274d-4616-946e-ea5cc2e25067

**Comment by vitor251093** [comment]
I may have fixed this issue with my latest master commit

**Comment by sandwichwater** [comment]
i cant test on windows at the moment as that build is still bugged but i could probably set up a virtual machine to check

**Comment by vitor251093** [comment]
I think I fixed that bug with the latest master version as well.

**Comment by sandwichwater** [comment]
flickering is fixed but it still shows incorrect emphasis on guest play

**Comment by vitor251093** [comment]
Ah yes, sorry about that. Just commited that fix as well.

**Comment by sandwichwater** [comment]
yep its fixed👍
