### ISSUE TITLE
EUR rom not working

### ISSUE THREAD

**Issue by migyanari** [vitor251093/KHDays_FM#37]
Hi, I have dumped the ROM from my original cartridge with a 3DS and the game works propertly in the original melonDS, is there any problem with it in this modification of the emulator? It says "Failed to loadthe ROM". If a obtain from other resources an USA ROM, then it works fine.

I'm trying on Windows 10, and I don't know if there is more info I can provide

Thanks in advance

**Comment by vitor251093** [comment]
@migyanari could you confirm if that issue still happens with KhDays Melon Mix 0.2.0 (the latest release)?

**Comment by migyanari** [comment]
Hi there! With the new version I'm able to load the ROM but it seems the Language selected in the Firmware settings is ignored and it keeps loading the game in english (I'm trying with the spanish language).

**Comment by vitor251093** [comment]
Good to know that it's loading! I will check the language issue

**Comment by vitor251093** [comment]
@migyanari sorry for the wait. Just managed to figure out the source of the issue. Can you check if the issue still happens with this build?

https://github.com/vitor251093/KHDays_FM/actions/runs/8290966218

**Comment by migyanari** [comment]
It's working perfectly with that build, thank you :)
