### ISSUE TITLE
Mission select screen description shows where the minimap would usually be

### ISSUE THREAD

**Issue by ReidArsenault** [vitor251093/KHDays_FM#38]
When on the mission select screen in story mode, rather than showing the top and bottom screen side to side, it shows the bottom screen where the minimap would be, causing it to be cut off and descriptions unreadable.

EDIT: For some odd reason it started working on Mission 22, will update if it stops working again.
EDIT2: Very next mission it stopped working, I'm going to keep track of which missions seem to work and which ones don't as I go.
EDIT3: Seems to work specifically when Beast's Castle is selected

**Comment by vitor251093** [comment]
This issue will be handled by #18
