### ISSUE TITLE
windows issue is happening again with latest builds

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#44]

**Comment by vitor251093** [comment]
Hey @sandwichwater ! Good to see you!

I will check this out.

**Comment by sandwichwater** [comment]
good to see you too ! 

> Does that apply to the last build from yesterday as well?

unfortunately yes , as for why im unsure as i cant see any changes made that would reintroduce this bug , atleast nothing that looks like it

**Comment by sandwichwater** [comment]
actually , im wondering if the latest changes made to fix the segmentation fault is what broke the windows version again ¿ just that it wouldnt make too much sense considering a segmentation fault is what caused the bug in the first place so fixing it should make it runable . very weird

**Comment by vitor251093** [comment]
@sandwichwater could you check if the latest build is working?

**Comment by sandwichwater** [comment]
hrm , doesnt seem to be unfortunately

**Comment by vitor251093** [comment]
@sandwichwater can you make a new test? I think I managed to fix the Segmentation Fault for good this time

**Comment by sandwichwater** [comment]
yep it works ! will start testing out scenarios to make sure everything works properly

**Comment by sandwichwater** [comment]
alright , made a compilation of everything ive found so far : #58

**Comment by vitor251093** [comment]
Alright. Let's deal with them in the other issue and close this one
