### ISSUE TITLE
Followed Windows build Instructions for a STATIC .exe, fails to load, says missing DLLs

### ISSUE THREAD

**Issue by PrincessKeba** [vitor251093/KHDays_FM#54]
Hi, I built the latest build on Windows using MSYS64 and followed the instructions on the front page. I tried building the DYNAMIC build first and when launching KHDaysMM.exe I get no window, task manager pops up with the program for a moment then closes. I then tried building the STATIC build and it says I'm missing DLLs. (I was under the impression it didn't need DLLs for that build, like normal MelonDS.)

All the dependencies were installed with no problem and it seemed to build with no errors other than a deprecated JIT it skipped. I want to use the new features as the last release had issues like the shop and mission screen displaying the bottom screen on the minimap. If I could get help, please, that would be great.

**Comment by sandwichwater** [comment]
this unfortunately seems to be an ongoing issue with an unknown cause considering it was fixed months ago , its not really clear whats causing it again . only with the windows build too

**Comment by vitor251093** [comment]
@PrincessKeba can you confirm if this issue no longer happens with you?

**Comment by vitor251093** [comment]
Both build processes should be working as expected right now. If we can confirm that this bug is back, we can reopen this issue
