### ISSUE TITLE
0.2.0 bugs

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#66]
not as many thistime !

when paused in a cutscene , a black bar displays at the bottom , likely related to the mission gauge as its in the same spot the mission gauge goes during gameplay
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/b416d515-582d-4efb-a25d-e39c0ec54e05)

game seems to change to dual screen mode at random from screen transitions . doesnt seem to be consistent in what causes it either with no directly apparent cause

https://github.com/vitor251093/KHDays_FM/assets/70611518/0bb45ec0-c72f-4668-b9b0-6577778332c1

https://github.com/vitor251093/KHDays_FM/assets/70611518/859fba0d-da42-478b-aa28-3df4eb0655f1

panels menu shows only one screen

https://github.com/vitor251093/KHDays_FM/assets/70611518/839039ba-630a-44c7-8feb-dfacfdbc17c0

also related to panels , no panel icons appear on the results screen
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/7db6434f-2e6b-478b-b8bb-edc72ec42542)

**Comment by vitor251093** [comment]
I think I managed to fix most of those. The only exception is the "no panel icons appear on the results screen" one. That one will be a little more complicated.

**Comment by sandwichwater** [comment]
seem to still get random switches to dual screen mode , and now the menu bugs out too
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/07bc4eed-d888-4215-bc76-fb5957299094)

it also seems that the panels disappear in the panels menu too for some reason , which i think is what was causing the original panel menu bug in the first place . no panels (which are part of the 3d engine) means that it couldnt detect any 3d objects for the game to switch to dual mode
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/0d3c098b-f4e7-4e40-8b67-14395a2e2912)

pausing during cutscenes doesnt display a black bar anymore though👍

**Comment by vitor251093** [comment]
Regarding the menu bug and the random switches: I definitively need to work on #51 ...

Regarding the panel menu bug: I will work on that as well.

**Comment by vitor251093** [comment]
@sandwichwater , now they should be fixed xD

Or at least, I hope so

**Comment by sandwichwater** [comment]
seem to be fixed yep !
