### ISSUE TITLE
mission mode bugs

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#67]
select mission screen bugs out whenever you complete a or exit out of a mission in mission mode , with seemingly all characters on all missions 
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/b0e8d86c-ff4e-43e5-bfc8-72b8459807f4)

screen bugs out when selecting missions in different worlds , the only ones that arent affected seem to be twilight town , the world that never was , agrabah , and olympus
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/d77a796f-51f1-4b90-b17c-357f9ba5d15e)

**Comment by vitor251093** [comment]
Fixed both in the master branch

**Comment by sandwichwater** [comment]
works perfectly👍
