### ISSUE TITLE
Command menu down command not working as intended 

### ISSUE THREAD

**Issue by Organizationguy** [vitor251093/KHDays_FM#68]
https://github.com/vitor251093/KHDays_FM/assets/152083249/9520148d-9c17-41ef-9bc5-1c899bb892d8

Going up works fine, but down moves roxas before moving the command menu. I'm using the .ini made by ench for the steam deck but added the up and down the up and down options for the command menu.

**Comment by vitor251093** [comment]
I don't have a SteamDeck, so I'm not familiar with melonDS's UI on it, but it seems like "Hat 1 Down" is attached to both command menu down and directional down, isn't it? Or am I misinterpreting the UI?

**Comment by Organizationguy** [comment]
It's running the windows version the emulator, but it sets the D-pad and the joystick inputs as the same in both Hat/Axis. I also tried adding the left and right command menu navigation to see how they are working and pressing right moves roxas and left moves him and makes him jump. Maybe mapping everything in keyboard mode rather than controller mode would avoid whatever is triggering it?

**Comment by vitor251093** [comment]
That could work. Sorry, I'm really not used to the SteamDeck, so I can only guess possible solutions.

**Comment by Organizationguy** [comment]
Manually assigning keyboard commands and mapping them in the deck interface seems to have worked, but while I was doing it I found that using the left and right command menu buttons triggers A and B respectively. Is this a seperate bug do you think? You could make the left and right situation specific like you did with the command menu navigation but invert it so that it is only active when not in the field for navigating the title screen and whatnot.

**Comment by vitor251093** [comment]
That's actually a known bug (#50). I still couldn't fix it, but it's already being investigated :)

**Comment by Organizationguy** [comment]
Cool. Also has there been changes in the recognition of the day "title cards". Day 9 doesnt want to go full screen for me?

**Comment by vitor251093** [comment]
> Cool. Also has there been changes in the recognition of the day "title cards". Day 9 doesnt want to go full screen for me?

That's not one of the tracked bugs. Can you please create a new bug for that attaching a screenshot/picture?

**Comment by sandwichwater** [comment]
went ahead and made a new issue for that : #70 , has another related bug
