### ISSUE TITLE
Corrupted save files

### ISSUE THREAD

**Issue by migyanari** [vitor251093/KHDays_FM#69]
Hello, when the game is opened with the last version of the emulator (0.2), it can't load previous save files that are correctly loaded with the original melonDS:
![corrupt](https://github.com/vitor251093/KHDays_FM/assets/48485652/7277f0db-1a98-481f-a4e9-b49492f1033d)

This bug it's happening with both the EUR and USA ROMs.

**Comment by vitor251093** [comment]
I've experienced that as well. Although, it seems to be related with saving/loading the same data with ROMs from different regions. Example: creating a new save with the US version, loading with the EUR version, saving the US save with the EUR version, then trying to load that save with the US ROM.

Can you confirm if your scenario may have been caused by a similar scenario?

**Comment by migyanari** [comment]
Hi, sorry but the scenario it's not similar. I have two save files exported from my original game, one from the past year, with 3 internal save files from long ago, and another one exported today, with one main difference. It has a more recent internal save file, that, for some reason, appears as not corrupted:
![semicorrupted](https://github.com/vitor251093/KHDays_FM/assets/48485652/5f29c92b-626e-484f-b4cb-9b00e9dc98e5)

As I said, this save file has been exported today, and the only internal save that is correctly working is from a few months ago. I don't know if it's related to the problem or it could be something else (like the day I am, for example), but I suppose it's worth noticing.

**Comment by vitor251093** [comment]
@migyanari sorry for taking so long to answer.

Can you confirm if the issue also happens if you build the base_melonds branch from the source?

**Comment by migyanari** [comment]
Hello again, don't need to apologize at all :)

The melonDS built with the base_melonds branch has the language error reported in [#37#issuecomment-1950472557](https://github.com/vitor251093/KHDays_FM/issues/37#issuecomment-1950472557) (ignores the Spanish firmware selection) but it shows the saves allright:
![melon build](https://github.com/vitor251093/KHDays_FM/assets/48485652/6cc8dff7-3b49-40ff-9c06-1b0dd9bac58e)

**Comment by vitor251093** [comment]
That's quite confusing, considering not much changed in the emulator core. Can you please send that save file here, so I can reproduce the issue here?

**Comment by migyanari** [comment]
There you go, hope it helps: [save.zip](https://github.com/vitor251093/KHDays_FM/files/14897860/save.zip)

**Comment by vitor251093** [comment]
I figured it out!! It seems that is being caused by the cheats. Disabling them and restarting fixes the issue.

Maybe it's conflicting with the cheats of other regions. I will use the recently introduced methods that allow me to add cart conditions to fix that.

**Comment by vitor251093** [comment]
I've disabled the "X + D-Pad" cheat for now, until I can make it work without causing bugs. The "X + D-Pad" cheat issue will be handled at #88
