### ISSUE TITLE
minimap changes to white when dialogue boxes pop up

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#75]
thankfully doesnt happen during cutscenes , only field interactions
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/0fb6edfd-5da9-456f-921c-63204c0fa90d)

**Comment by vitor251093** [comment]
I just realized the minimap update may also have broken the bosses extra life bar indicators, because I moved it up a little bit, but I still need to confirm that

**Comment by vitor251093** [comment]
Fixed both issues
