### ISSUE TITLE
Steam Deck support

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#78]
A SteamDeck build would be a very interesting addition. Maybe an Arch Linux build would work out of the box?

This guide isn't based on the latest version, but it may still work:

https://gist.github.com/enchywastaken/f79288a16973ef51ba07415ffb402d87

It may be used as a reference to create the default ini file. The ini file probably isn't mapping the command menu yet though.

It's unconfirmed, but maybe the AppImage build already works on the SteamDeck.

**Comment by vitor251093** [comment]
@OrganizationGuy could you confirm if the latest AppImage build works on the SteamDeck?

**Comment by Organizationguy** [comment]
Can confirm that it is booting in a running in game.

**Comment by vitor251093** [comment]
Perfect then! In that case it just needs the automatic mapping for SteamDeck, which will be done by #32, and an explanation on how to use it on the README file.

I should be able to update the README file tomorrow, and then this ticket will be closed.

**Comment by Organizationguy** [comment]
Something I did notice though is that there is some slight graphical flicker. That could just be the 5x resolution being to high for it so I will need to test it.

**Comment by vitor251093** [comment]
Let me know if you have the chance to test. We can analyze the possibility of decreasing the default value

**Comment by vitor251093** [comment]
Does the flicker stops if you use 3x?

**Comment by sandwichwater** [comment]
i might be wrong but i think thats just a melonds issue in general due to how their opengl renderer is , if a character is too far away the hair and face rendering gets all wonky 

but again i could be wrong and it may very well be a new issue

**Comment by vitor251093** [comment]
@Organizationguy could you also please share the configured ini file, so I can add the joy configs as default for SteamDeck devices?

**Comment by Organizationguy** [comment]
I think sandwichwater is right, tred it at 2x and 1x as well as 3x and it still happened. I probably didnt notice it before

**Comment by vitor251093** [comment]
Alright then :)

In that case, we just need to sort out the default ini contents to finish this issue. Can you help me with that?

**Comment by Organizationguy** [comment]
Im tring to find the ini file for the app image version but I cant figure where it has been placed. Any suggestions? I could screenshot the controls screen? The ini I made for the windows version isnt necessary, it works fine to set the controls via the gamepad in melonds, rather than setting them to keyboard commands and using the steam interface to bind the keybinds to the pad as I had done before.

**Comment by vitor251093** [comment]
The ini file should be at ~/.config/khDaysMM/melonDS.ini

Screenshots of the controls screen unfortunately won't be enough. In order to set these controls as the default, I need the controls IDs rather than their names.

**Comment by Organizationguy** [comment]
Found it. Here you go:

Key_A=-1
Key_B=-1
Key_Select=-1
Key_Start=-1
Key_Right=-1
Key_Left=-1
Key_Up=-1
Key_Down=-1
Key_R=-1
Key_L=-1
Key_X=-1
Key_Y=-1
Joy_A=0
Joy_B=1
Joy_Select=6
Joy_Start=7
Joy_Right=131071
Joy_Left=1179647
Joy_Up=17956863
Joy_Down=16908287
Joy_R=5
Joy_L=4
Joy_X=3
Joy_Y=2
HKKey_Lid=-1
HKKey_Mic=-1
HKKey_Pause=-1
HKKey_Reset=-1
HKKey_FastForward=-1
HKKey_FastForwardToggle=-1
HKKey_FullscreenToggle=-1
HKKey_SwapScreens=-1
HKKey_SwapScreenEmphasis=-1
HKKey_SolarSensorDecrease=-1
HKKey_SolarSensorIncrease=-1
HKKey_FrameStep=-1
HKKey_PowerButton=-1
HKKey_VolumeUp=-1
HKKey_VolumeDown=-1
HKJoy_Lid=-1
HKJoy_Mic=-1
HKJoy_Pause=35782655
HKJoy_Reset=-1
HKJoy_FastForward=-1
HKJoy_FastForwardToggle=-1
HKJoy_FullscreenToggle=86114303
HKJoy_SwapScreens=-1
HKJoy_SwapScreenEmphasis=-1
HKJoy_SolarSensorDecrease=-1
HKJoy_SolarSensorIncrease=-1
HKJoy_FrameStep=-1
HKJoy_PowerButton=-1
HKJoy_VolumeUp=-1
HKJoy_VolumeDown=-1
Key_TouchRight=-1
Key_TouchLeft=-1
Key_TouchUp=-1
Key_TouchDown=-1
Joy_TouchRight=50462719
Joy_TouchLeft=51511295
Joy_TouchUp=68288511
Joy_TouchDown=67239935
Key_CmdMenuLeft=-1
Key_CmdMenuRight=-1
Key_CmdMenuUp=-1
Key_CmdMenuDown=-1
Joy_CmdMenuLeft=258
Joy_CmdMenuRight=264
Joy_CmdMenuUp=257
Joy_CmdMenuDown=260
JoystickID=0
WindowWidth=1280
WindowHeight=800
WindowMax=0
ScreenRotation=0
ScreenGap=0
ScreenLayout=2
ScreenSwap=0
ScreenSizing=3
IntegerScaling=0
ScreenAspectTop=3
ScreenAspectBot=0
ScreenFilter=1
ScreenUseGL=0
ScreenVSync=0
ScreenVSyncInterval=1
3DRenderer=1
Threaded3D=1
GL_ScaleFactor=5
GL_BetterPolygons=0
LimitFPS=1
MaxFPS=1000
AudioSync=0
ShowOSD=1
AutoFullscreen=1
ConsoleType=0
DirectBoot=1
JIT_Enable=0
JIT_MaxBlockSize=32
JIT_BranchOptimisations=1
JIT_LiteralOptimisations=1
JIT_FastMemory=1
ExternalBIOSEnable=0
BIOS9Path=
BIOS7Path=
FirmwarePath=
DSiBIOS9Path=
DSiBIOS7Path=
DSiFirmwarePath=
DSiNANDPath=
DLDIEnable=0
DLDISDPath=dldi.bin
DLDISize=0
DLDIReadOnly=0
DLDIFolderSync=0
DLDIFolderPath=
DSiSDEnable=0
DSiSDPath=dsisd.bin
DSiSDSize=0
DSiSDReadOnly=0
DSiSDFolderSync=0
DSiSDFolderPath=
FirmwareOverrideSettings=0
FirmwareUsername=melonDS
FirmwareLanguage=1
FirmwareBirthdayMonth=1
FirmwareBirthdayDay=1
FirmwareFavouriteColour=0
FirmwareMessage=
FirmwareMAC=
MPAudioMode=1
MPRecvTimeout=25
LANDevice=
DirectLAN=0
SavStaRelocSRAM=0
AudioInterp=0
AudioBitDepth=0
AudioVolume=256
DSiVolumeSync=0
MicInputType=1
MicDevice=
MicWavPath=
LastROMFolder=/home/deck/Emulation/roms/nds
LastBIOSFolder=
RecentROM_0=/home/deck/Emulation/roms/nds/Kingdom Hearts - 358-2 Days.nds
RecentROM_1=rom/game.nds
RecentROM_2=
RecentROM_3=
RecentROM_4=
RecentROM_5=
RecentROM_6=
RecentROM_7=
RecentROM_8=
RecentROM_9=
SaveFilePath=
SavestatePath=
CheatFilePath=
EnableCheats=1
MouseHide=1
MouseHideSeconds=2
PauseLostFocus=0
RTCOffset=0
DSBatteryLevelOkay=1
DSiBatteryLevel=15
DSiBatteryCharging=1
DSiFullBIOSBoot=0
GdbEnabled=0
GdbPortARM7=3334
GdbPortARM9=3333
GdbARM7BreakOnStartup=0
GdbARM9BreakOnStartup=0
Camera0_InputType=0
Camera0_ImagePath=
Camera0_CamDeviceName=
Camera0_XFlip=0
Camera1_InputType=0
Camera1_ImagePath=
Camera1_CamDeviceName=
Camera1_XFlip=0

**Comment by vitor251093** [comment]
That's it! Thank you! Just added the Steam Deck default controls.

Now the game should be completely functional on the Steam Deck on the first startup, with no additional steps other than launching the game, unless the players want to do some custom tweaks by themselves.
