### ISSUE TITLE
display bug with text cutscenes containing only a black screen

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#80]
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/79f06f2a-5737-4425-ac99-4e5f4b0d9ae9)

**Comment by vitor251093** [comment]
Definitely related with the return of bug #70

**Comment by vitor251093** [comment]
Change reverted. @sandwichwater can you confirm if the issue is solved for you as well?

**Comment by sandwichwater** [comment]
huhm , the credits did revert but this issue still remains . on the other side though , the roxas thoughts and day counter is working properly again

**Comment by vitor251093** [comment]
Which day causes this cutscene exactly?

**Comment by sandwichwater** [comment]
sorry for the late response , the effect can be seen in days 26 (terminated) , 50 (a familiar sound) , and 297 (contact)

**Comment by vitor251093** [comment]
@sandwichwater I managed to fix those three scenarios. Can you check if everything is alright right now?

I mean, except for the credits, those are definitively still broken lol

**Comment by sandwichwater** [comment]
yep all are fixed👍
