### ISSUE TITLE
incorrect screen display when withdrawing from or completing a mission

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#85]
i couldve sworn i reported this bug months ago yet when i went to go comment on the issue i couldnt find it , oh well lol . happening on latest build , seems to happen when the hub area is both the grey area and twilight town
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/6b5fcca9-6996-4e40-ba0c-1ff9f20e8449)

**Comment by vitor251093** [comment]
This issue should be fixed now.
