### ISSUE TITLE
movement is a little too precise

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#86]
movement sensitivity seems to be ramped up to 1000% , even just slightly touching the joystick without pushing it in any direction seems to move roxas , making it very difficult to control . this also effects menus making it incredibly hard to navigate them

**Comment by vitor251093** [comment]
I know why that happened. melonDS ignores 50% of the analog stick axis, and I changed that to 6.25% when adding sensibility for the camera.

Should be an easy fix.

**Comment by vitor251093** [comment]
Fixed it. The next build should have less sensitive controls.
