### ISSUE TITLE
Option to also have the mission gauge appear on the hud under the new minimap

### ISSUE THREAD

**Issue by RainyNyte** [vitor251093/KHDays_FM#87]
Just think it would be nice to see the mission progress in real time without having to pause the game to check it since a good chunk of the game revolves around full clearing each mission. Understandably a fairly low priority tweak, but one that would be nice nonetheless.

**Comment by vitor251093** [comment]
Interesting. But where exactly would it be placed? Can you please illustrate where you envision it on screen, exactly?

**Comment by RainyNyte** [comment]
took me a bit to get around to this but here's a real quick mock up for what I was thinking
![mock-up](https://github.com/vitor251093/KHDays_FM/assets/155491229/2a546d84-ee72-4162-a45d-788b754e795c)

**Comment by vitor251093** [comment]
Ah, I see now. That will require moving other elements a little bit, but it may be doable.

It will probably look better if I can remove the black background. I can actually take advantage of the black background to create a shadow, like the one in the top left element.

I will see what I can do.

**Comment by sandwichwater** [comment]
this may be something that should have a toggle , its a helpful addition but i feel like its bordering the more cluttered side , especially when you start incorporating more players and mission sigils//death counter , some people may prefer to not have it show , a toggle could probably be made in #55

**Comment by vitor251093** [comment]
Change was covered by #120
