### ISSUE TITLE
Black screen Bug

### ISSUE THREAD

**Issue by DragonKing2356** [vitor251093/KHDays_FM#89]
During the intro cutscene that plays sanctuary when it gets to roxas most of it is not shown with a black screen. but you hear the scene continue.

**Comment by sandwichwater** [comment]
this is a display mode issue due to how the game detects when the bottom screen goes black , it should be fixed when we figure out cutscene replacement

**Comment by vitor251093** [comment]
Like mentioned, this will be eventually fixed by #9
