### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by sedef122** [vitor251093/KHDays_FM#91]
I used the app image build on my steam deck and it seems to fine. I was able to play for over 20 hours with no issues but now the game randomly crashes. Now sure if anything be done about it.

**Comment by vitor251093** [comment]
Try enabling the JIT Recompiler. See if that fixes the issue

**Comment by sedef122** [comment]
Tried it and it did work for awhile, longer periods without crashing but it sill froze

**Comment by vitor251093** [comment]
Does the freezing happens more frequently during any specific moments, such as battles/transitions/cutscenes?

**Comment by sedef122** [comment]
It only seems to happen during combat and when I am doing an action, be that casting a spell or just attacking.

**Comment by vitor251093** [comment]
Try this: disable the cheats, and see if the bug persists. The game will look stretched (since that will also disable the widescreen hack) and you may need to enable the X + directional option in the game menu in order to use the command menu, but I think that may fix the bug.

**Comment by vitor251093** [comment]
@sedef122 could you make that test?

**Comment by sedef122** [comment]
Apologies for not getting back to you sooner. I disabled cheats and from that point have had no further crashes in the 10-15 hours I have played since doing so.

**Comment by vitor251093** [comment]
So it really is related to the cheat bug. Damn.

I will create a new label to keep track of that.

**Comment by vitor251093** [comment]
I've disabled the "X + D-Pad" cheat for now, until I can make it work without causing bugs. The "X + D-Pad" cheat issue will be handled at #88
