### ISSUE TITLE
0.2.1 release crashes on launch (windows)

### ISSUE THREAD

**Issue by Yulvex** [vitor251093/KHDays_FM#92]
Good evening! I downloaded the exe, dragged the copy of the game in the rom folder, but i only get a black window for a few seconds before it closes. What do i need to solve this?

**Comment by vitor251093** [comment]
Open Windows Command line (cmd) and start MelonMix from it. It should output some logs which may help us identify the problem

**Comment by BrainFartScientist** [comment]
I have the same problem and I tried it with the command line but there was no output, it just crashes.

**Comment by vitor251093** [comment]
> I have the same problem and I tried it with the command line but there was no output, it just crashes.

Does Melon Mix launches if you rename the "rom" folder to something else? (The game won't open that way, but I'm trying to figure out if the issue is at the startup, or at the ROM loading process)

**Comment by BrainFartScientist** [comment]
No it doesn't either way. I suppose emulator doesn't start

**Comment by BrainFartScientist** [comment]
It creates a .txt document called "shaderfail" in the same folder. Not sure if that helps

**Comment by vitor251093** [comment]
Shaderfail? That means the shader is failing to compile. This actually helps. Two questions:

1. Is that Windows running inside a virtual machine?
2. If it isn't running inside a virtual machine, which is your computer's graphic card?

**Comment by BrainFartScientist** [comment]
1. No 
2. NVIDIA 1050 TI

**Comment by sandwichwater** [comment]
whats your cpu ¿ im running a 1050ti and it runs fine for me , maybe its a cpu issue ¿

**Comment by vitor251093** [comment]
@BrainFartScientist could you please send the shaderfail.txt file here? If it's a log, it may contain useful information for debugging the issue

**Comment by Ookami32194** [comment]
I have a similar issue, but, in my case, I think it's due to "cmake -B build" giving "-bash: cmake: command not found" when in mysy2

**Comment by Yulvex** [comment]
> It creates a .txt document named "shaderfail" in the same folder. Not sure if that helps

Oh yeah, I saw that. I'll share it next time I'm on my pc

**Comment by vitor251093** [comment]
Seems like it's just the contents of the shader.

Since we have no output of the application itself, I'll need to store the output of glGetShaderInfoLog inside a text file, so we can figure out what exactly went wrong.

**Comment by Yulvex** [comment]
> Owner

I see... Will try to see if i can build the program to see if there are differences

**Comment by vitor251093** [comment]
@Yulvex can you confirm if the issues persists with the latest Actions builds?

**Comment by Yulvex** [comment]
> @Yulvex can you confirm if the issues persists with the latest Actions builds?

I'll check when I'm home

**Comment by Yulvex** [comment]
Downloaded the latest release and still no dice. Let's see if i can experiment with building

**Comment by vitor251093** [comment]
We started using a custom fragment shader since 0.2.1, so that's probably related.

I just made a change that should save the error messages to shaderfail log files:
https://github.com/vitor251093/KHDays_FM/actions/runs/9212668455

It should be available here once it stops building. That should give us more insight on the issue.

**Comment by Yulvex** [comment]
> We started using a custom fragment shader since 0.2.1, so that's probably related.
> 
> I just made a change that should save the error messages to shaderfail log files: https://github.com/vitor251093/KHDays_FM/actions/runs/9212668455
> 
> It should be available here once it stops building. That should give us more insight on the issue.

Thanks! I'm really happy to finally have a way to witness this game, but i'll keep helping where i can

**Comment by Yulvex** [comment]
[shaderfail-fragment-CompositorShader.log](https://github.com/vitor251093/KHDays_FM/files/15421305/shaderfail-fragment-CompositorShader.log)
Here is the doc i got on the other build

**Comment by vitor251093** [comment]
```
0(596) : error C1020: invalid operands to "*"
0(614) : error C1020: invalid operands to "*"
0(644) : error C1020: invalid operands to "*"
0(663) : error C1020: invalid operands to "*"
```

This should be very helpful. I will check that at night.

**Comment by vitor251093** [comment]
I see a pattern already. Every time I multiply a magic float number by u3DScale, it causes the error. If I move those to const float variables, that may fix the issue.

**Comment by vitor251093** [comment]
Just made a new build. Check if this one fix the issue:
https://github.com/vitor251093/KHDays_FM/actions/runs/9215181577

**Comment by vitor251093** [comment]
I had a report that this may have fixed the issue. Could you please confirm if this has fixed the issue to you as well @Yulvex ?

**Comment by Yulvex** [comment]
It now finally works! Thank you so much for your all the work you've been putting so far, it's amazing
