### ISSUE TITLE
macOS not building correctly

### ISSUE THREAD

**Issue by InochiPM** [vitor251093/KHDays_FM#95]
Im getting an error that states [ -- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) ]
and it would build a broken melonDS app that cant be opened. 
When i tried to re-build it now im getting a completely different error. 
![Screenshot 2024-05-17 at 5 24 26 PM](https://github.com/vitor251093/KHDays_FM/assets/13459080/f7929c7a-7138-478b-855b-d2640a48d8a6)

Also for the macOS installation guide you seem to be missing the mac-bundle.rb file for making it a standalone.

**Comment by epic-bruh-moment** [comment]
just download the artifact in actions tab, under workflow macOS

**Comment by vitor251093** [comment]
The instructions were copied from the melonDS repo. It seems the file is missing there as well.

As implied by the fact that the Actions builds are working, the GitHub workflow is actually functional.

https://github.com/vitor251093/KHDays_FM/blob/master/.github/workflows/build-macos.yml

I can use it as a reference to update the instructions.

**Comment by vitor251093** [comment]
I managed to fix the manual build (except for the mac-bundle.rb part), but it seems that melonDS is also producing broken builds right now, so I will need to figure out how to fix that

**Comment by vitor251093** [comment]
Based on my tests, everything that currently works on melonDS's master branch should also work here. Although, if it fails for melonDS (Actions builds, missing mac-bundle.rb file) it will fail here as well.

I will make a manual macOS build for the next release. For the other two issues, we are going to wait for melonDS to fix for now, but I will create a new issue so we can keep track of that

**Comment by vitor251093** [comment]
> I will make a manual macOS build for the next release.

So, that was the plan, but I just realized I can create bundled macOS apps either, only those which require the Homebrew dependencies...

Local builds should work, like the one you tried to do, but it won't work without the Homebrew dependencies for now. That will also be handled at #146
