### ISSUE TITLE
Game Studdering on Steamdeck in Game Mode

### ISSUE THREAD

**Issue by aceofspades230** [vitor251093/KHDays_FM#96]
The SteamDeck version of the game runs perfectly in Desktop Mode but when running the game in Game Mode, it studders pretty bad. Tried enabling the JIT Recompiler but didn't resolve the issue. I also tried to change the 3D Render from OpenGL to Software but that messes up the display setup.

**Comment by vitor251093** [comment]
> The SteamDeck version of the game runs perfectly in Desktop Mode but when running the game in Game Mode, it studders pretty bad.

I'm unfamiliar with Steam Deck's Game Mode. What is it?

> I also tried to change the 3D Render from OpenGL to Software but that messes up the display setup.

Yeah, most of the visual changes rely on the OpenGL renderer.

**Comment by aceofspades230** [comment]
> > The SteamDeck version of the game runs perfectly in Desktop Mode but when running the game in Game Mode, it studders pretty bad.
> 
> I'm unfamiliar with Steam Deck's Game Mode. What is it? Sorry, I don't have a Steam Deck.
> 
> > I also tried to change the 3D Render from OpenGL to Software but that messes up the display setup.
> 
> Yeah, most of the visual changes rely on the OpenGL renderer.

The Steam Deck's Gaming Mode is the device's main mode that is used for just launching games from your Steam Library. If there is an app that is on the Deck, it can be added to your Steam Library and then launched from Gaming Mode. Its similar to Steam's Big Picture Mode.

**Comment by vitor251093** [comment]
Well, in that case, I can only guess what may be the matter. Is that issue also present with regular melonDS, or only with the Melon Mix?

**Comment by aceofspades230** [comment]
I figured it out. It was the frame limit settings that I had enabled and I had it set to 40. Turning it off resolves the issue. Thank you.

**Comment by Aheenr** [comment]
> I figured it out. It was the frame limit settings that I had enabled and I had it set to 40. Turning it off resolves the issue. Thank you.

How did you turn off the frame limiter??
