### ISSUE TITLE
My command menu does not work and repeat other inputs

### ISSUE THREAD

**Issue by UltimoSucco** [vitor251093/KHDays_FM#97]
In practice, with all the right settings, so for the PS4 controller the 14, 15, 12 and 13 buttons, my game moves Roxas back and forth and with the left and right respectively he jumps and attacks.

I don't know if I'm the first to experience this problem but I've tried everything to fix it, without success. 

Pls HELP

**Comment by sandwichwater** [comment]
make sure control type b is enabled , it shouldve been enabled by default but apparently thats bugged so you may need to enable it manually . left and right being attack is an intentional workaround to get around the ds not having enough buttons to have command menu navigation via dpad

**Comment by UltimoSucco** [comment]
I understand, in this case it works as it should, also I realized that the game doesn't allow you to move the cursor if the command is gray so what I thought was a problem with the emulator is instead a limitation of the game, mea culpa

**Comment by vitor251093** [comment]
In that case, I will close this issue. But, in case you stumble with any issues involving the D-Pad, fell free to reopen it :)
