### ISSUE TITLE
Button to show the lower screen

### ISSUE THREAD

**Issue by ZLGNF** [vitor251093/KHDays_FM#98]
Given how so many missions on this game rely on killing a specific Heartless you haven't seen in the previous ones, I think it's best to have a button to show the lower screen to see the picture of the Heartless we have to kill... and I guess also a bigger version of the map. 

I think this is a better solution than having that picture + mission progress cluttering the gameplay screen.

**Comment by vitor251093** [comment]
So a kind of Mission Details button? I would say that makes sense. Maybe we can combine that with #87 and have some kind of temporary HUD toggle.

Like, while you hold said button, the map is replaced with the target + mission progress, and when you release it, the map is immediately back. That would drop the requirement of adding a new setting, while providing both informations.

What do you think @sandwhichwater ?

**Comment by RainyNyte** [comment]
I like the idea, it honestly seems like the best solution to all the different issues people have raised pertaining to the mission details so far

**Comment by RainyNyte** [comment]
I mean, the proposed changes wouldnt necessarily be any more complex than adding in a minimap that previously didn't exist, the one that is currently in use doesn't seem to be the one from vanilla

**Comment by vitor251093** [comment]
> Ideally, the player wouldn't be using this button in the middle of combat. Maybe you could have the game paused when you click this button and change screens, but that would only help in single player.

Well, in that case I could just add that to the pause screen, like the mission progress. I mean, if it's going to be paused anyway

> The other suggestions would require more complex changes in the UI that may or may not be possible...

Oh, they are definitely possible. I can guarantee that.

> or look good tbh

That's the harder part lol

But we managed to make the minimap look good enough in my opinion, so we may also find a way to achieve that with the other elements. We just need to figure how they should look.

Their position was worrying me the most, but with the idea of toggling the HUD, we have room for more elements.

> And then, there's also the missions where you simply collect hearts which just show a picture of the world you are in.

It will be easier to keep the same behavior in that case as well, so the toggle/hold would show the picture of the world

**Comment by vitor251093** [comment]
> I mean, the proposed changes wouldnt necessarily be any more complex than adding in a minimap that previously didn't exist, the one that is currently in use doesn't seem to be the one from vanilla

It actually is 😄 I just applied the negative effect to whatever was a shade of gray, and applied the gradient effect to the borders, using the fragment shader

But this is exactly why I think this won't be a problem. I can take similar approaches to achieve a functional good look

**Comment by vitor251093** [comment]
Change was covered by #120
